Fast
pact-foundation/pact-php pull request #316
Opened 2023-06-12 04:27 UTC by slt

Pact consumer tests are supposed to be like unit tests but mine were taking 2 seconds+ each, the majority of which was php sleep()

* Allow SetHealthCheckRetrySec / PACT_MOCK_SERVER_HEALTH_CHECK_RETRY_SEC
  to be a float so it can be set to 0.1 instead of 1.

* Use usleep instead of sleep so that the retry seconds can be a < 1 second.

* Increase the total number of attempts so it still tries for ~10 seconds.

* Remove sleeps when PactMessage which do not appear to be needed.

2023-06-12 05:35 UTC, mefellows commented
This is great, thanks for all of these PR's @slt. I'm not qualified to review the PHP bits, so will wait for a maintainer - but just wanted to pass on my gratitude.

2023-07-14 16:12 UTC, YOU54F requested changes
the linter is failing, I've noted a comment

2023-07-14 16:12 UTC, YOU54F commented on src/PhpPact/Standalone/MockService/MockServer.php
> +                \usleep(round($retrySec * 1000000));
round returns a float and usleep expects an int

https://www.php.net/manual/en/function.round.php
https://www.php.net/manual/en/function.usleep.php

`usleep(intval(round($retrySec * 1000000)));`

2023-07-14 16:14 UTC, YOU54F commented
Kicked off a build https://github.com/pact-foundation/pact-php/actions/runs/5556096016

2023-07-14 16:46 UTC, YOU54F commented
complete in https://github.com/pact-foundation/pact-php/pull/322

2023-07-14 16:46 UTC, closed without merging